spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/youddit
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
